### ISSUE TITLE
[Question]Reverse a linked list using recursion(Famous interview question)

### ISSUE THREAD

**Issue by KAUSHIK-DEKA** [biswas-neelesh96/C-Cpp-Scripts-2021#4]
Can you assign this to me?

**Comment by biswas-neelesh96** [comment]
Kaushik, I've checked your code, it's good and I've merged into my repository. Rest, Tushar you can choose another program or if you want to change any portion in the code, you can also do it, All the very best for Hacktoberfest 2021!

Regards,
Neelesh

**Comment by tushar152** [comment]
Ok, I raised PR today, please merge that asap.

**Comment by aman8094** [comment]
please assign me .
